### ISSUE TITLE
Local storage spanning mutiple disks wrong size

### ISSUE THREAD

**Issue by Haribo112** [xcp-ng/host-installer_old#16]
Hi,

When installing XCP-NG it gives the option to create a local storage repository that spans all disks you select. In my case, I selected 2 SSDs. One is 256 GB in size, the other 128GB. After installation is done, XCP reports that there is one storage repository available, with a size of only 152GB. My expectation was that it would be 256+128-<xcp install size> (XCP is installed on the smaller of the two drives). 

Did I do something wrong? Do I have a wrong understanding of how this works? And finally, would it be possible for me to remove this storage repository and create a new one with just the 256GB SSD?

**Comment by olivierlambert** [comment]
Hi,

For "general purpose" questions, it's better [to use our forum](https://xcp-ng.org/forum) and keep the Github repo free for identified issues/problems.

To answer quickly your question, the system will take around 60GiB for itself. I would advise to use the first SSD for the system, and not "span", keep the 256GiB only as a local ext SR.
