### ISSUE TITLE
No such file or directly: '/EULA' after answerfile installation

### ISSUE THREAD

**Issue by pietrushnic** [xcp-ng/host-installer_old#18]
I'm trying answerfile automated installation using xcp-ng-8.0 and after installation getting the following screen:
![IMG_20200326_125320](https://user-images.githubusercontent.com/1071894/77644316-19961b00-6f61-11ea-959a-bb155d5bc1ba.jpg)

My answer file: https://gist.github.com/pietrushnic/6cd46cfc32d41be0f60bc65595649601

Answerfile [documentation](https://github.com/xcp-ng/host-installer/blob/master/doc/answerfile.txt) says nothing about EULA or licensing at all. If this is a bug I can try to fix it in answerfile.py.

**Comment by stormi** [comment]
Thanks for the feedback. This is a benign known bug. Just press Enter. It is fixed in XCP-ng 8.1.

**Comment by stormi** [comment]
By the way, if you can check the fix, the latest pre-release ISOs are available at https://updates.xcp-ng.org/isos/8.1/

**Comment by pietrushnic** [comment]
@stormi it doesn't boot and complains for the configuration that I'm using for booting (my grub.cfg):

```
echo "insmod efinet"
insmod efinet
sleep 2
echo "call net_dhcp"
net_dhcp
sleep 2

echo "tftp load xen.gz..."
multiboot2 (tftp,$net_efinet0_dhcp_next_server)/xen.gz dom0_mem=1024M,max:1024M watchdog dom0_max_vcpus=4 com1=115200,8n1 console=com1,vga
echo "tftp load vmlinuz..."
module2 (tftp,$net_efinet0_dhcp_next_server)/vmlinuz console=hvc0 console=tty0  answerfile=https://gist.githubusercontent.com/pietrushnic/6cd46cfc32d41be0f60bc65595649601/raw/a5a754e0927e553aeae27ff312763e0e1a5109b9/xpc-ng-answerfile install
#module2 (tftp,$net_efinet0_dhcp_next_server)/vmlinuz console=hvc0 console=tty0 install
echo "tftp load install.img..."
module2 (tftp,$net_efinet0_dhcp_next_server)/install.img
echo "booting..."
boot
```
I made picture of 2 "problems":
![IMG_20200326_163458](https://user-images.githubusercontent.com/1071894/77665878-88cf3780-6f80-11ea-95e1-3d0d62a50c77.jpg)
![IMG_20200326_163517](https://user-images.githubusercontent.com/1071894/77665886-8bca2800-6f80-11ea-9bdb-ae7e34e1d531.jpg)

**Comment by pietrushnic** [comment]
@stormi finally I was able to boot 8.1, definitely, there was a problem with tftp, but then I tried GRUB 2.04 using its tftp and http support. Performance of GRUB TFTP and HTTP modules is terrible, I will get to address that with maintainer, maybe on GRUB and 3mdeb minisummit 2020. So I switched to ipxe, the problem here was that there is not multiboot2 support, so we applied some old patches (2017) and those worked if anyone interested [iPXE multiboot2 UEFI suport](https://github.com/3mdeb/ipxe/tree/mb2_uefi) - maybe we will be able to merge that upstream.

Finally, HTTP performance in iPXE is very good and I was able to boot XCP-ng 8.1 prefinal2. the problem mentioned in this issue no longer occurs, but I faced different message, which requires accepting:
![IMG_20200329_171951](https://user-images.githubusercontent.com/1071894/77853063-49a02100-71e2-11ea-83eb-4e933f393dc4.jpg)

So the situation was improved because we have no error, but we still need user interaction. Can I get some rationale behind that decision? Can we assume the system would be usable without accepting? Can we extend answerfile to cover that license?

**Comment by stormi** [comment]
This behaviour is inherited from Citrix. I guess it's a legal requirement. You could open an issue asking for an enhancement, or even contribute it. Please describe the context and try to give an idea of the value of such a change for users.

The text doesn't look good though, looks like the text is all mixed.

**Comment by stormi** [comment]
If I remember correctly, when the answerfile contains a password hash for the root user, then this screen is not displayed. Could be a workaround. You can still change the password afterwards.
