### ISSUE TITLE
Raid problem

### ISSUE THREAD

**Issue by kocimiros** [xcp-ng/host-installer_old#6]
I have created 2x raid 1...  (2x SSD 120GB) + (2x HDD 500 GB) in my raid controller.
had these 2 virtual drives 120 and 500gb and started xcp-ng installer, but instead of 2 virtual drives I have seen 4 physical drives in step, where I choose drive to put installation on. There was an option to create software raid, so I tried it. Selected 2 (same) 120gb drives and pushed OK button. It did nothing, so I tried the same action with 2 500gb drives and I was able to create software raid. But I wonder why it didn't work with 120GB SSDs and why it didn't show my virtual drives from my raid controller at all. 

(Fujitsu primergy tx100 s3)
Thanks.

**Comment by olivierlambert** [comment]
What kind of RAID controller it is? If it's a kind of "software RAID", it's possible it's not recognized by the kernel during the installer phase.

Maybe disable all RAID options in your BIOS, and try again the soft RAID1 in the install.

**Comment by kocimiros** [comment]
Fujitsu primergy tx100 s3 is just home server for streaming movies,... 
it has no physical raid controller card (in pci slot). It is probably just some integrated feature in motherboard. 
I have tried to disable raid controller in bios (selected AHCI) and use only software raid, but it didn't work as well on SSDs.
coul'd be the size a problem ?

**Comment by olivierlambert** [comment]
1. Yes, motherboard fake-RAID must be disabled, because it's not well supported
2. No, the size is OK.

Maybe you should wipe those disk to be sure there isn't any leftover from the previous fake-RAID. You can do that by fill them with 0 (with dd command) and when it's clean, try again XCP-ng RAID on both 120GiB SSD.

**Comment by kocimiros** [comment]
Thank you ! I put new pair of SSDs and used only software raid and it works just fine.

**Comment by olivierlambert** [comment]
Thanks for your feedback, enjoy XCP-ng :+1:
