### ISSUE TITLE
Failed to run efibootmgr: Could not set variable Boot0005: No space left on device

### ISSUE THREAD

**Issue by keegandent** [xcp-ng/host-installer_old#7]
I'm trying to just do a basic fresh install of XCP-ng 7.6.0. The drives in question are a hardware mirror (using a proper Dell PERC H710 controller) of 500GB drives. The exact message is shown below.

![image](https://user-images.githubusercontent.com/25830144/54263489-f4459300-453e-11e9-8d55-ddb69a1cf62d.png)

As you can see, it occurs at about 50% of the way through the final installation stage.

![image](https://user-images.githubusercontent.com/25830144/54263561-1b9c6000-453f-11e9-9752-912da608978b.png)

I'm not sure what the issue could be. I disabled write caching on the controller and any other settings I thought might interfere, but I'm not having any luck at all. Any ideas on how to proceed from here?

**Comment by stormi** [comment]
You can access console logs and/or a linux shell by pressing `ALT+RIGHT ARROW` and see if there's anythink useful.

**Comment by Fohdeesha** [comment]
I have many XCP-ng 7.6.0 installs on this exact hardware (dell servers with H710 hardware raid) without issue. Judging by the message, I would assume this is an issue with the EFI/EUFI boot and/or installer, as all my installs have been BIOS. Can you check your BIOS settings and see if boot type is set to either BIOS or EFI?

**Comment by keegandent** [comment]
Yes my settings are for (U)EFI boot mode. Is that installation mode experimental for XCP-ng? I’ve installed RHEL server using EFI on this particular machine before and didn’t have a problem. I will try a BIOS installation instead. Will I still be able to run EFI Virtual Machines if XCP-ng is installed using BIOS/MBR?

**Comment by keegandent** [comment]
So I succeeded in installing in BIOS mode without any real issues other than the fact I couldn't seem to add the drive to my boot order and had to select it manually on each reboot, but I think that's unrelated. I then went back to install via UEFI to replicate the issue and get additional logs for @stormi , but it also somehow succeeded. I'm at a complete loss, but I guess this issue is in error or that the installer needs to wipe more thoroughly on a fresh install?

**Comment by stormi** [comment]
Maybe the drives already had an EFI boot partition and the installer chose to reuse it but there was not enough space in it?

**Comment by imperialspice** [comment]
The current way I solve this issue is by using an efi shell, you can probably find an ISO to burn somewhere online; alternatively I think that arch and kali have one in there installers, and the bcfg command. The arch wiki [here](https://wiki.archlinux.org/index.php/Unified_Extensible_Firmware_Interface#bcfg) has a good explanation of how to do this.

**Comment by keegandent** [comment]
Marking as OBE (Old But Everlasting)
